apiVersion: v1
data:
  controller.plugin_artifacts_broker.image: quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0
  controller.plugin_registry.url: ""
  controller.webhooks.enabled: "true"
  devworkspace.api_sidecar.image: quay.io/che-incubator/che-api-sidecar:next
  devworkspace.default_routing_class: basic
  devworkspace.experimental_features_enabled: "true"
  devworkspace.routing.cluster_host_suffix: ""
  devworkspace.sidecar.image_pull_policy: Always
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-configmap
  namespace: devworkspace-controller
