# Add webhooks to the devfile/api CRDs
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devworkspaces.workspace.devfile.io
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: devworkspace-operator
          # Note: service name is hard-coded in pkg/webhook/server/server.go
          name: devworkspace-webhookserver
          path: /convert
        # caBundle will be filled by Service CA operator
        caBundle: Cg==
---
# Add webhooks to the devfile/api CRDs
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devworkspacetemplates.workspace.devfile.io
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: devworkspace-operator
          # Note: service name is hard-coded in pkg/webhook/server/server.go
          name: devworkspace-webhookserver
          path: /convert
        # caBundle will be filled by Service CA operator
        caBundle: Cg==
