apiVersion: v1
kind: ConfigMap
metadata:
  name: che-workspace-controller
  namespace: che-workspace-controller
data:
  ingress.global.domain: apps-crc.testing
  plugin.registry.url: http://che-plugin-registry.apps-crc.testing/v3
  che.workspace.plugin_broker.artifacts.image: quay.io/eclipse/che-plugin-artifacts-broker:v3.1.0
  cherestapis.image.name: quay.io/dfestal/che-workspace-crd-rest-apis:newone
