apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: view-workspaces
rules:
  - apiGroups:
      - workspace.che.eclipse.org
    resources:
      - workspaces
    verbs:
      - get
      - list
      - watch
