apiVersion: v2
publisher: eclipse
name: cloud-shell
version: nightly
type: Che Editor
displayName: Cloud Shell Editor
title: Cloud Shell Editor
description: Cloud Shell provides an ability to use terminal widget like an editor.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/eclipse/che-machine-exec/
firstPublicationDate: "2020-01-29"
category: Other
spec:
  endpoints:
  - name: cloud-shell
    public: true
    targetPort: 4444
    attributes:
      protocol: http
      type: ide
      path: /static/
      discoverable: false
      secure: true
      cookiesAuthEnabled: true
  containers:
  - name: che-machine-exec
    image: "${RELATED_IMAGE_plugin_eclipse_cloud_shell_nightly}"
    ports:
    - exposedPort: 4444
    command: ["/go/bin/che-machine-exec",
              "--authenticated-user-id", "$(DEVWORKSPACE_CREATOR)",
              "--idle-timeout", "$(DEVWORKSPACE_IDLE_TIMEOUT)",
              "--pod-selector", "controller.devfile.io/workspace_id=$(CHE_WORKSPACE_ID)",
              "--static", "/cloud-shell"]
