apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "workspace.che.eclipse.org/v1alpha1",
          "kind": "Workspace",
          "metadata": {
            "name": "java-mysql"
          },
          "spec": {
            "started": false,
            "devfile": {
              "apiVersion": "1.0.0",
              "projects": [
                {
                  "name": "web-java-spring-petclinic",
                  "source": {
                    "location": "https://github.com/spring-projects/spring-petclinic.git",
                    "type": "git"
                  }
                }
              ],
              "commands": [
                {
                  "actions": [
                    {
                      "command": "mvn clean install",
                      "component": "tools",
                      "type": "exec",
                      "workdir": "${CHE_PROJECTS_ROOT}/web-java-spring-petclinic"
                    }
                  ],
                  "name": "maven build"
                },
                {
                  "actions": [
                    {
                      "command": "SPRING_DATASOURCE_URL=jdbc:mysql://db/petclinic \\\nSPRING_DATASOURCE_USERNAME=petclinic \\\nSPRING_DATASOURCE_PASSWORD=password \\\njava -jar -Dspring.profiles.active=mysql \\\n-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 \\\ntarget/*.jar\n",
                      "component": "tools",
                      "type": "exec",
                      "workdir": "${CHE_PROJECTS_ROOT}/web-java-spring-petclinic"
                    }
                  ],
                  "name": "run webapp"
                },
                {
                  "actions": [
                    {
                      "command": "/opt/rh/rh-mysql57/root/usr/bin/mysql -u root < ${CHE_PROJECTS_ROOT}/web-java-spring-petclinic/src/main/resources/db/mysql/user.sql && /opt/rh/rh-mysql57/root/usr/bin/mysql -u root -D petclinic < ${CHE_PROJECTS_ROOT}/web-java-spring-petclinic/src/main/resources/db/mysql/schema.sql && echo -e '\\e[32mDone.\\e[0m Database petclinic was prepared!'",
                      "component": "mysql",
                      "type": "exec"
                    }
                  ],
                  "name": "prepare database"
                },
                {
                  "actions": [
                    {
                      "referenceContent": "{\n\"version\": \"0.2.0\",\n\"configurations\": [\n  {\n    \"type\": \"java\",\n    \"name\": \"Debug (Attach) - Remote\",\n    \"request\": \"attach\",\n    \"hostName\": \"localhost\",\n    \"port\": 5005\n  }]\n}\n",
                      "type": "vscode-launch"
                    }
                  ],
                  "name": "Debug remote java application"
                }
              ],
              "components": [
                {
                  "id": "redhat/java/latest",
                  "memoryLimit": "1280MiB",
                  "type": "chePlugin",
                  "volumes": [
                    {
                      "containerPath": "/home/user/.m2",
                      "name": "m2"
                    }
                  ]
                },
                {
                  "alias": "tools",
                  "endpoints": [
                    {
                      "name": "8080/tcp",
                      "port": 8080
                    }
                  ],
                  "env": [
                    {
                      "name": "JAVA_OPTS",
                      "value": "-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user"
                    },
                    {
                      "name": "MAVEN_OPTS",
                      "value": "$(JAVA_OPTS)"
                    }
                  ],
                  "image": "quay.io/eclipse/che-java8-maven:7.8.0",
                  "memoryLimit": "700Mi",
                  "mountSources": true,
                  "type": "dockerimage",
                  "volumes": [
                    {
                      "containerPath": "/home/user/.m2",
                      "name": "m2"
                    }
                  ]
                },
                {
                  "alias": "mysql",
                  "endpoints": [
                    {
                      "attributes": {
                        "discoverable": "true",
                        "public": "false"
                      },
                      "name": "db",
                      "port": 3306
                    }
                  ],
                  "env": [
                    {
                      "name": "MYSQL_USER",
                      "value": "petclinic"
                    },
                    {
                      "name": "MYSQL_PASSWORD",
                      "value": "password"
                    },
                    {
                      "name": "MYSQL_DATABASE",
                      "value": "petclinic"
                    },
                    {
                      "name": "PS1",
                      "value": "$(echo ${0})\\\\$"
                    }
                  ],
                  "image": "centos/mysql-57-centos7",
                  "memoryLimit": "300Mi",
                  "mountSources": true,
                  "type": "dockerimage"
                },
                {
                  "alias": "theia-ide",
                  "id": "eclipse/che-theia/latest",
                  "type": "cheEditor"
                },
                {
                  "id": "eclipse/che-machine-exec-plugin/latest",
                  "type": "chePlugin"
                }
              ]
            }
          }
        },
        {
          "apiVersion": "workspace.che.eclipse.org/v1alpha1",
          "kind": "WorkspaceRouting",
          "metadata": {
            "labels": {
              "che.workspace_id": "workspacee200e582a7ab43c6"
            },
            "name": "workspacee200e582a7ab43c6"
          },
          "spec": {
            "exposed": true,
            "ingressGlobalDomain": "192.168.99.100.nip.io",
            "routingClass": "",
            "services": {
              "che-machine-exec": {
                "endpoints": [
                  {
                    "attributes": {
                      "cookiesAuthEnabled": "true",
                      "discoverable": "false",
                      "protocol": "ws",
                      "public": "true",
                      "secure": "true",
                      "type": "terminal"
                    },
                    "name": "che-machine-exec",
                    "port": 4444
                  }
                ],
                "serviceName": "servere200e582a7ab43c6-che-machine-exec"
              },
              "mysql": {
                "endpoints": [
                  {
                    "attributes": {
                      "discoverable": "true",
                      "public": "false"
                    },
                    "name": "db",
                    "port": 3306
                  }
                ],
                "serviceName": "servere200e582a7ab43c6-mysql"
              },
              "theia-ide": {
                "endpoints": [
                  {
                    "attributes": {
                      "cookiesAuthEnabled": "true",
                      "discoverable": "false",
                      "protocol": "http",
                      "public": "true",
                      "secure": "true",
                      "type": "ide"
                    },
                    "name": "theia",
                    "port": 3100
                  },
                  {
                    "attributes": {
                      "discoverable": "false",
                      "protocol": "http",
                      "public": "true",
                      "type": "ide-dev"
                    },
                    "name": "theia-dev",
                    "port": 3130
                  },
                  {
                    "attributes": {
                      "discoverable": "false",
                      "protocol": "http",
                      "public": "true"
                    },
                    "name": "theia-redirect-1",
                    "port": 13131
                  },
                  {
                    "attributes": {
                      "discoverable": "false",
                      "protocol": "http",
                      "public": "true"
                    },
                    "name": "theia-redirect-2",
                    "port": 13132
                  },
                  {
                    "attributes": {
                      "discoverable": "false",
                      "protocol": "http",
                      "public": "true"
                    },
                    "name": "theia-redirect-3",
                    "port": 13133
                  }
                ],
                "serviceName": "servere200e582a7ab43c6-theia-ide"
              },
              "tools": {
                "endpoints": [
                  {
                    "attributes": {
                      "public": "true"
                    },
                    "name": "8080/tcp",
                    "port": 8080
                  }
                ],
                "serviceName": "servere200e582a7ab43c6-tools"
              }
            },
            "workspacePodSelector": {
              "che.original_name": "workspace",
              "che.workspace_id": "workspacee200e582a7ab43c6"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/internal-objects: '["workspaceroutings.workspace.che.eclipse.org","components.workspace.che.eclipse.org"]'
    categories: Developer Tools
    containerImage: quay.io/che-incubator/che-workspace-controller:nightly
    createdAt: "2020-05-27T05:12:57Z"
    certified: "false"
    description: |
      Start an Eclipse Che 7 workspace based on a Devfile description,
      that provides all required information related to the project
      development environment
    repository: https://github.com/che-incubator/che-workspace-operator
    support: Red Hat
  name: che-workspace-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Component is the Schema for the components API
      kind: Component
      name: components.workspace.che.eclipse.org
      version: v1alpha1
    - description: WorkspaceRouting is the Schema for the workspaceroutings API
      kind: WorkspaceRouting
      name: workspaceroutings.workspace.che.eclipse.org
      version: v1alpha1
    - description: |
        Eclipse Che 7 workspace based on a Devfile description,
        that provides all required information related to the project
        development environment
      displayName: Che Workspace
      kind: Workspace
      name: workspaces.workspace.che.eclipse.org
      version: v1alpha1
      specDescriptors:
      - description: Expected status
        displayName: Started
        path: started
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: Workspace status
        displayName: Status
        path: phase
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase
      - description: URL to have access to the online IDE
        displayName: IDE URL
        path: ideUrl
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      - description: Workspace ID
        displayName: ID of the Workspace
        path: workspaceId
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Conditions of the workspace activity
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
  displayName: Che Workspace Operator
  description: |
    Start an Eclipse Che 7 workspace based on a Devfile description,
    that provides all required information related to the project
    development environment
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - workspace.che.eclipse.org
              resources:
                - workspaces
                - workspaceroutings
                - components
              verbs:
                - create
                - delete
                - deletecollection
                - patch
                - update
          serviceAccountName: edit-workspaces
        - rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - watch
                - list
                - get
                - create
                - update
                - patch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
              verbs:
                - watch
                - list
                - get
                - create
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
              verbs:
                - list
                - get
                - watch
            - apiGroups:
                - apps
                - extensions
              resources:
                - deployments
                - replicasets
              verbs:
                - '*'
            - apiGroups:
                - extensions
              resources:
                - ingresses
              verbs:
                - '*'
            - apiGroups:
                - ""
                - route.openshift.io
              resources:
                - routes
              verbs:
                - create
                - delete
                - deleteCollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
                - route.openshift.io
              resources:
                - routes/custom-host
              verbs:
                - create
            - apiGroups:
                - ""
                - route.openshift.io
              resources:
                - routes/status
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - che-workspace-controller
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - workspace.che.eclipse.org
              resources:
                - '*'
                - workspaceroutings
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - create
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - mutatingwebhookconfigurations
                - validatingwebhookconfigurations
              verbs:
                - '*'
            - apiGroups:
                - oauth.openshift.io
              resources:
                - oauthclients
              verbs:
                - create
                - get
                - delete
                - list
                - patch
                - update
                - watch
                - deletecollection
          serviceAccountName: che-workspace-controller
        - rules:
            - apiGroups:
                - workspace.che.eclipse.org
              resources:
                - workspaces
                - workspaceroutings
                - components
              verbs:
                - get
                - list
                - watch
          serviceAccountName: view-workspaces
      deployments:
        - name: che-workspace-controller
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: che-workspace-controller
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: ""
                labels:
                  app: che-workspace-controller
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: che-workspace-operator
                    image: quay.io/che-incubator/che-workspace-controller:nightly
                    imagePullPolicy: Always
                    name: che-workspace-controller
                    ports:
                      - containerPort: 8443
                        name: webhook-server
                    resources: {}
                serviceAccountName: che-workspace-controller
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - workspaces
  - devtools
  - developer
  - ide
  - che
  maintainers:
  - email: dfestal@redhat.com
    name: David Festal
  - email: jpinkney@redhat.com
    name: Josh Pinkney
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/che-incubator/che-workspace-operator/
  version: 1.0.0
