apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
  name: no-dockerimage-component
spec:
  started: true
  devfile:
    apiVersion: 0.0.1
    metadata:
      name: no-dockerimage
    components:
      - alias: cloud-shell
        type: cheEditor
        id: eclipse/cloud-shell/nightly

