apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-controller
  namespace: che-workspace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-workspace-controller
  template:
    metadata:
      labels:
        app: che-workspace-controller
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
    spec:
      serviceAccountName: che-workspace-controller
      containers:
        - name: che-workspace-controller
          image: quay.io/che-incubator/che-workspace-controller:nightly
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-workspace-operator"
          ports:
            - name: webhook-server
              containerPort: 8443
