apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-workspace-controller
  template:
    metadata:
      labels:
        app: che-workspace-controller
        app.kubernetes.io/name: devworkspace-controller
        app.kubernetes.io/part-of: devworkspace-controller
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
    spec:
      serviceAccountName: che-workspace-controller
      containers:
        - name: che-workspace-controller
          image: quay.io/che-incubator/che-workspace-controller:nightly
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-workspace-operator"
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_nightly
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_dev_4_5_0
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_dev_nightly
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_eclipse_cloud_shell_nightly
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_web_terminal_tooling
              value: "registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8:2.1"
            - name: RELATED_IMAGE_openshift_oauth_proxy
              value: "openshift/oauth-proxy:latest"
          ports:
            - name: webhook-server
              containerPort: 8443
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: webhook-tls-certs
          projected:
            sources:
              - configMap:
                  name: devworkspace-controller-secure-service
                  items:
                    - key: service-ca.crt
                      path: ./ca.crt
              - secret:
                  name: devworkspace-controller
