bases:
- ../components/manager
- ../components/rbac
- ../crd

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: configmap
  envs:
  - config.properties

patchesStrategicMerge:
- manager_image_patch.yaml
- manager_dev_mode_patch.yaml

vars:
- name: OPERATOR_NAMESPACE
  objref:
    kind: Deployment
    group: apps
    version: v1
    name: manager
  fieldref:
    fieldpath: metadata.namespace
