# This patch adds an environment variable to the workspace deployment
# to enable dev mode
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: devworkspace-controller
        env:
        - name: DEVELOPMENT_MODE
          value: "true"
