# This patch sets the image used for deployment according to environment variables.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: devworkspace-controller
        image: ${IMG}
        imagePullPolicy: Always
        env:
          - name: RELATED_IMAGE_devworkspace_webhook_server
            value: ${IMG}
